const USER="Myisse",PASS="Mamour229@";const $=id=>document.getElementById(id);
let resellers=JSON.parse(localStorage.getItem("ac_resellers")||"null")||[],tickets=JSON.parse(localStorage.getItem("ac_tickets")||"null")||[];
const save=()=>{localStorage.setItem("ac_resellers",JSON.stringify(resellers));localStorage.setItem("ac_tickets",JSON.stringify(tickets))};
const money=n=>Number(n).toLocaleString("fr-FR")+" F";
const dateNow=()=>new Date().toISOString().slice(0,10);
function render(){ $("resellerCount").textContent=resellers.length;$("ticketCount").textContent=tickets.length;let used=tickets.filter(t=>t.status==="Utilisé");$("usedCount").textContent=used.length;$("revenue").textContent=money(used.reduce((s,t)=>s+Number(t.plan),0));
$("resellerTable").innerHTML=resellers.map(r=>{let ts=tickets.filter(t=>t.resellerId===r.id),u=ts.filter(t=>t.status==="Utilisé");return `<tr><td><b>${r.name}</b></td><td>${r.code}</td><td>${r.zone}</td><td>${ts.length}</td><td>${u.length}</td><td>${money(u.reduce((s,t)=>s+Number(t.plan),0))}</td></tr>`}).join("")||'<tr><td colspan="6">Aucun revendeur.</td></tr>';
$("ticketReseller").innerHTML=resellers.map(r=>`<option value="${r.id}">${r.name} — ${r.zone}</option>`).join("");$("ticketFilter").innerHTML='<option value="all">Tous</option>'+resellers.map(r=>`<option value="${r.id}">${r.name}</option>`).join("");renderTickets();renderStats()}
function renderTickets(){let f=$("ticketFilter").value||"all",a=f==="all"?tickets:tickets.filter(t=>t.resellerId===f);$("ticketTable").innerHTML=a.slice().reverse().map(t=>`<tr><td><b>${t.code}</b></td><td>${t.resellerName}</td><td>${t.zone}</td><td>${money(t.plan)}</td><td>${t.status}</td><td>${t.date}</td></tr>`).join("")||'<tr><td colspan="6">Aucun ticket.</td></tr>'}
function renderStats(){let p=$("period").value,cut=p==="all"?Infinity:Number(p),rows=resellers.map(r=>{let a=tickets.filter(t=>t.resellerId===r.id&&t.status==="Utilisé"&&(p==="all"||((Date.now()-new Date(t.date))/86400000)<=cut));return{r,n:a.length,ca:a.reduce((s,t)=>s+Number(t.plan),0)}}).filter(x=>x.n).sort((a,b)=>b.ca-a.ca);$("statsTable").innerHTML=rows.map(x=>`<tr><td><b>${x.r.name}</b></td><td>${x.r.zone}</td><td>${x.n}</td><td>${money(x.ca)}</td></tr>`).join("")||'<tr><td colspan="4">Aucune vente enregistrée.</td></tr>'}
$("loginForm").onsubmit=e=>{e.preventDefault();if($("user").value===USER&&$("pass").value===PASS){$("login").classList.add("hidden");$("app").classList.remove("hidden")}else alert("Identifiant ou mot de passe incorrect.")};
$("logout").onclick=()=>location.reload();
$("addReseller").onclick=()=>$("modal").classList.remove("hidden");$("close").onclick=()=>$("modal").classList.add("hidden");
$("resellerForm").onsubmit=e=>{e.preventDefault();let name=$("rName").value.trim(),code=$("rCode").value.trim().toUpperCase(),zone=$("rZone").value.trim();if(resellers.some(r=>r.code===code)){alert("Ce code existe déjà.");return}resellers.push({id:String(Date.now()),name,code,zone});save();render();e.target.reset();$("modal").classList.add("hidden")};
$("generate").onclick=()=>{if(!resellers.length){alert("Ajoute d'abord un revendeur.");return}let r=resellers.find(x=>x.id===$("ticketReseller").value),plan=$("ticketPlan").value,q=Math.min(500,Math.max(1,Number($("ticketQty").value)||1));for(let i=0;i<q;i++)tickets.push({code:`AC-${r.code}-${plan}-${Date.now().toString(36).toUpperCase()}-${String(i+1).padStart(3,"0")}`,resellerId:r.id,resellerName:r.name,zone:r.zone,plan,status:"Disponible",date:dateNow()});save();render();alert(`${q} ticket(s) généré(s) pour ${r.name}.`)};
$("ticketFilter").onchange=renderTickets;$("period").onchange=renderStats;render();
